In [62]:
import matplotlib.pyplot as plt
import pandas as pd
df = pd.read_csv('author_ru_utf.csv', sep = ',', encoding = 'utf8')
df.head()

,Unnamed: 0,document,на,что,за,и,в,из,со,а,...,о,ко,над,без,при,об,через,из-за,из-под,Author
0,1,ГогольНВ_ВечераЧ1_1.txt,154,95,42,309,157,40,8,46,...,5,1,6,10,5,4,1,0,0,ГогольНВ
1,2,ГогольНВ_ВечераЧ1_2.txt,179,158,71,413,233,40,8,53,...,15,2,4,8,11,7,5,1,0,ГогольНВ
2,3,ГогольНВ_ВечераЧ1_3.txt,164,140,52,363,214,29,4,49,...,10,3,5,4,12,4,6,1,1,ГогольНВ
3,4,ГогольНВ_ВечераЧ2_1.txt,172,160,42,370,211,50,7,60,...,9,3,6,12,11,10,4,0,0,ГогольНВ
4,5,ГогольНВ_ВечераЧ2_2.txt,171,129,43,331,183,41,7,67,...,13,3,8,12,6,3,7,5,1,ГогольНВ

In [63]:
# Заменяем авторов на числа
print(list(set(df['Author'])))
authors_dict = {}
for i in range(len(list(set(df['Author'])))):
    authors_dict.update({list(set(df['Author']))[i]: i})
print(authors_dict)
df['Author'] = df['Author'].replace(authors_dict)
df.head()

['ГончаровИА', 'ГогольНВ', 'ДостоевскийФМ', 'ТолстойЛН']
{'ГончаровИА': 0, 'ГогольНВ': 1, 'ДостоевскийФМ': 2, 'ТолстойЛН': 3}

C:\Users\ilso61\AppData\Local\Temp\ipykernel_9976\4156632388.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Author'] = df['Author'].replace(authors_dict)

,Unnamed: 0,document,на,что,за,и,в,из,со,а,...,о,ко,над,без,при,об,через,из-за,из-под,Author
0,1,ГогольНВ_ВечераЧ1_1.txt,154,95,42,309,157,40,8,46,...,5,1,6,10,5,4,1,0,0,1
1,2,ГогольНВ_ВечераЧ1_2.txt,179,158,71,413,233,40,8,53,...,15,2,4,8,11,7,5,1,0,1
2,3,ГогольНВ_ВечераЧ1_3.txt,164,140,52,363,214,29,4,49,...,10,3,5,4,12,4,6,1,1,1
3,4,ГогольНВ_ВечераЧ2_1.txt,172,160,42,370,211,50,7,60,...,9,3,6,12,11,10,4,0,0,1
4,5,ГогольНВ_ВечераЧ2_2.txt,171,129,43,331,183,41,7,67,...,13,3,8,12,6,3,7,5,1,1

In [64]:
# матрица корреляций
correlation_matrix = df.loc[:, 'на':'Author'].corr()
correlation_matrix.style.background_gradient(cmap='coolwarm')

In [65]:
# Перемешаем значения, чтобы случайно выбирать тестовую выборку
df = df.sample(frac=1).reset_index(drop=True)
df.head()

,Unnamed: 0,document,на,что,за,и,в,из,со,а,...,о,ко,над,без,при,об,через,из-за,из-под,Author
0,113,ДостоевскийФМ_Бесы_10.txt,74,77,27,240,139,11,14,56,...,17,3,3,4,4,5,0,1,0,2
1,435,ТолстойЛН_Воскр_7.txt,85,99,23,327,167,23,6,41,...,25,3,2,3,10,2,5,0,3,3
2,258,ДостоевскийФМ_Подросток_1.txt,39,86,14,149,85,13,4,30,...,15,1,2,8,9,7,2,1,0,2
3,346,ТолстойЛН_АннаКар_26.txt,96,175,42,401,189,24,12,37,...,51,3,2,1,5,5,5,4,1,3
4,223,ДостоевскийФМ_Идиот_12.txt,79,143,51,304,136,19,19,70,...,15,7,3,8,1,4,4,0,3,2

In [95]:
# Я объединил предлоги и союзы в группы по интегральной семе, ну +- СПОЙЛЕР не помогло улучшить
possession = ["с", "со", "без"] 
loc_in_space = ["при"]
dir_from = ["из-за", "из-под"] #["от", "из", "из-за", "из-под"]
dir_to = ["к", "ко", "до"]
move_by_obj = ["через", "по"] #
dir_loc = ["на", "в", "во", "под", "над", "за"] #
about = ["про"]
for_ = ["для"]
that = ["что"]
coord = ["и", "но", "а"]
# Теперь посчитаем суммы этих групп слов и сделаем их отдельными датафреймами, а не сериес обджектам, на всякий случай
Possession = pd.DataFrame(df.loc[:, possession].sum(axis=1))
Near = pd.DataFrame(df.loc[:, loc_in_space])
Dir_from = pd.DataFrame(df.loc[:, dir_from].sum(axis=1))
Move_by_obj = pd.DataFrame(df.loc[:, move_by_obj].sum(axis=1))
Dir_loc = pd.DataFrame(df.loc[:, dir_loc].sum(axis=1))
About = pd.DataFrame(df.loc[:, about].sum(axis=1))
For_ = pd.DataFrame(df.loc[:, for_])
That = pd.DataFrame(df.loc[:, that])
Coord = pd.DataFrame(df.loc[:, coord].sum(axis=1))
df_new = pd.concat([Possession,Near,Dir_from,Move_by_obj,Dir_loc,About,For_,That,Coord], axis = 1)
#df_new = pd.concat([Dir_from, Move_by_obj, About, Coord], axis = 1) Вот с этими параметрами получается также, как и с другими
df_new

       0  при  0   0    0   0  для  что    0
0     85    4  1  17  254   8    9   77  345
1    112   10  3  34  283   2   17   99  412
2     69    9  1  19  145   3   18   86  208
3    109    5  5  29  341  16   15  175  524
4    104    1  3  25  294  13    8  143  402
..   ...  ... ..  ..  ...  ..  ...  ...  ...
451  145    8  1  31  278  11   10  128  465
452  105    5  4  11  298  10   12  138  469
453  132    3  3  34  409   2   13  133  489
454  195   25  4  68  613  12   36  298  963
455  126   17  2  51  381   4   27  135  451

[456 rows x 9 columns]

In [96]:
from keras.models import Sequential
from keras.layers import Dense, Activation

import numpy as np

def get_model():
    # function returns the many-layered feedforward network
    # considers 9 floating point numbers as input
    # produces 2 floating point numbers as output
    model = Sequential()
    model.add(Dense(18, activation='relu', input_dim=9))
    # uncomment the following line to add one more layer
    # model.add(Dense(9, activation='relu'))
    model.add(Dense(2, activation='softmax'))
    model.compile(optimizer='adam',
                  loss='mean_squared_error',
                  metrics=['accuracy'])
    return model

def prepare_data(param_df, df_with_label): # переделал, чтобы лейблы загружались с исходного df, а параметры с df_new
    # function reads data from @filename
    # and returns six arrays: train data, train labels,
    # validation data, validation labels, test data and test labels
    input_data = np.ndarray(shape=(456, 9), dtype=float)
    output_data = np.ndarray(shape=(456, 1), dtype=float)
    input_data[:, :] = param_df.loc[:, :].to_numpy(dtype = float)
    output_data[:, :] = pd.DataFrame(df_with_label.loc[:, 'Author']).to_numpy(dtype = float)

    train_data = np.ndarray(shape=(273, 9), dtype=float)
    train_labels = np.ndarray(shape=(273, 1), dtype=float)
    train_data[:, :] = input_data[:273, :]
    train_labels[:, :] = output_data[:273, :]

    valid_data = np.ndarray(shape=(91, 9), dtype=float)
    valid_labels = np.ndarray(shape=(91, 1), dtype=float)
    valid_data[:, :] = input_data[273:364, :]
    valid_labels[:, :] = output_data[273:364, :]

    test_data = np.ndarray(shape=(92, 9), dtype=float)
    test_labels = np.ndarray(shape=(92, 1), dtype=float)
    test_data[:, :] = input_data[364:, :]
    test_labels[:, :] = output_data[364:, :]

    return train_data, train_labels, valid_data, valid_labels, test_data, test_labels

In [97]:
# getting data for both training and testing
train_data, train_labels, valid_data, valid_labels, test_data, test_labels = prepare_data(df_new, df)

print(train_data.shape)
print(train_labels.shape)
print(valid_data.shape)
print(valid_labels.shape)
print(test_data.shape)
print(test_labels.shape)

(273, 9)
(273, 1)
(91, 9)
(91, 1)
(92, 9)
(92, 1)

In [98]:
# creating a model
model = get_model()

# training a model
model.fit(train_data, train_labels, validation_data=(valid_data, valid_labels),
          epochs=100, batch_size=32)

# computing network predictions
predictions = model.predict_on_batch(test_data)

Epoch 1/100

C:\Users\ilso61\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

9/9 ━━━━━━━━━━━━━━━━━━━━ 2s 54ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 2/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 3/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 4/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 5/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 6/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 7/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 8/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 9/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 10/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 11/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 12/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 13/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 14/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 15/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 16/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 17/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 18/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 19/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 20/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 21/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 22/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 23/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 24/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 25/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 26/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 27/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 28/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 29/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 30/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 31/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 32/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 33/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 34/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 35/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 36/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 37/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 38/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 39/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 40/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 41/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 42/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 43/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 44/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 45/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 46/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 47/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 48/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 49/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 50/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 51/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 52/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 53/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 54/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 55/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 56/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 57/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 58/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 59/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 60/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 61/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 62/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 63/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 64/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 65/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 66/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 67/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 68/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 69/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 70/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 71/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 72/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 73/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 74/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 75/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 76/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 77/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 78/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 79/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 80/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 81/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 82/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 83/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 84/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 85/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 86/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 87/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 88/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 89/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 90/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 91/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 92/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 93/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 94/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 95/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 96/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 97/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 98/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 99/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176
Epoch 100/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.1245 - loss: 3.3132 - val_accuracy: 0.1758 - val_loss: 2.9176

In [99]:
# computing the percentage of correct predictions
res = 0.0
for i in range(test_data.shape[0]):
    if (test_labels[i, 0] == predictions[i, 0]):
        res += 1.0
res /= float(test_data.shape[0])

# printing resulting percentage
print('-------------------')
print(res * 100.0)
print('-------------------')

-------------------
8.695652173913043
-------------------